134130/intellij-mise

- modules/products/goland/src/main/kotlin/com/github/l34130/mise/go/GoLandProjectGoSdkSetup.kt
- src/main/resources/META-INF/mise-goland.xml
> Automatically load mise tools configuration when GoLand opened

- .idea/gradle.xml
- build.gradle.kts
- modules/core/src/main/kotlin/com/github/l34130/mise/settings/MiseConfigurable.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/settings/MiseSettings.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/settings/ui/RunConfigurationSettingsEditor.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/settings/ui/RunConfigurationSettingsPanel.kt
- modules/products/goland/src/main/kotlin/com/github/l34130/mise/runconfig/GoLandRunConfigurationExtension.kt
- modules/products/gradle/src/main/kotlin/com/github/l34130/mise/runconfig/GradleEnvironmentProvider.kt
- modules/products/idea/src/main/kotlin/com/github/l34130/mise/runconfig/IdeaRunConfigurationExtension.kt
- modules/products/nodejs/src/main/kotlin/com/github/l34130/mise/runconfig/NodeRunConfigurationExtension.kt
- modules/products/rider/build.gradle.kts
- modules/products/rider/src/main/kotlin/com/github/l34130/mise/runconfig/RiderPatchCommandLineExtension.kt
- settings.gradle.kts
- src/main/resources/META-INF/mise-goland.xml
- src/main/resources/META-INF/mise-gradle.xml
- src/main/resources/META-INF/mise-idea.xml
- src/main/resources/META-INF/mise-nodejs.xml
- src/main/resources/META-INF/mise-rider.xml
- src/main/resources/META-INF/plugin.xml
- ![image](https://github.com/user-attachments/assets/a857b082-a147-469b-bcb7-542b5dd40354)
> Support Rider run configurations

- modules/core/src/main/kotlin/com/github/l34130/mise/commands/MiseCmd.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/commands/MiseVersion.kt
> feat: Use `mise ls --offline`

- modules/products/nodejs/build.gradle.kts
- modules/products/nodejs/src/main/kotlin/com/github/l34130/mise/deno/ProjectDenoSetup.kt
- src/main/resources/META-INF/mise-deno.xml
- src/main/resources/META-INF/mise-javascript.xml
- Support auto-configuration form Deno
- Closes #50
> feat: Deno SDK support

- modules/products/nodejs/src/main/kotlin/com/github/l34130/mise/runconfig/NodeRunConfigurationExtension.kt
- Fix Mise's EnvVars are overriding runconfiguration's EnvVar table on nodejs.
- Mise's EnvVars must be applied on just Process.
> fix(nodejs): EnvVars are overriding runconfiguraion's

- modules/core/src/main/kotlin/com/github/l34130/mise/commands/MiseCmd.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/commands/MiseRunAction.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/commands/MiseTask.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/toolWindow/MisePanel.kt
- modules/products/toml/src/main/kotlin/com/github/l34130/mise/toml/completion/MiseConfigCompletionProvider.kt
- modules/products/toml/src/main/kotlin/com/github/l34130/mise/toml/completion/MiseConfigPsiUtils.kt
- modules/products/toml/src/main/kotlin/com/github/l34130/mise/toml/editor/MiseRunLineMarkerProvider.kt
- src/main/resources/META-INF/mise-toml.xml
> Add run button in mise.toml files

- modules/core/src/main/kotlin/com/github/l34130/mise/commands/MiseCmd.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/commands/MiseCmdExceptions.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/notifications/Notification.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/setups/AbstractProjectSdkSetup.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/toolWindow/MisePanel.kt
- modules/products/goland/src/main/kotlin/com/github/l34130/mise/runconfig/GoLandRunConfigurationExtension.kt
- modules/products/gradle/src/main/kotlin/com/github/l34130/mise/runconfig/GradleEnvironmentProvider.kt
- modules/products/idea/src/main/kotlin/com/github/l34130/mise/runconfig/IdeaRunConfigurationExtension.kt
- modules/products/nodejs/src/main/kotlin/com/github/l34130/mise/runconfig/NodeRunConfigurationExtension.kt
- modules/products/rider/src/main/kotlin/com/github/l34130/mise/runconfig/RiderPatchCommandLineExtension.kt
- modules/products/toml/src/main/kotlin/com/github/l34130/mise/toml/completion/MiseConfigCompletionProvider.kt
> feat: Trust config file with Button

- modules/core/src/main/kotlin/com/github/l34130/mise/core/command/MiseDevToolName.kt
> fix: Do not check DevTool name's lowercase

- modules/core/src/main/kotlin/com/github/l34130/mise/core/run/MiseRunConfigurationSettingsEditor.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/setting/MiseConfigurable.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/setting/MiseSettings.kt
- src/main/resources/META-INF/mise-deno.xml
- src/main/resources/META-INF/mise-goland.xml
- src/main/resources/META-INF/mise-idea.xml
- src/main/resources/META-INF/mise-nodejs.xml
- src/main/resources/META-INF/plugin.xml
- Closes #70 
- Support custom mise executable path. It auto detects from PATH default.
> feat: Support Mise executable customization

- modules/core/src/main/kotlin/com/github/l34130/mise/core/command/MiseCommandLine.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/command/MiseCommandLineHelper.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/command/MiseRunTaskOnTerminalAction.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/run/MiseRunConfigurationSettingsEditor.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/run/MiseRunConfigurationState.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/setting/MiseConfigurable.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/setting/MiseSettings.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/setup/AbstractProjectSdkSetup.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/toolwindow/nodes/MiseRootNode.kt
- modules/products/goland/src/main/kotlin/com/github/l34130/mise/goland/run/GoLandRunConfigurationExtension.kt
- modules/products/gradle/src/main/kotlin/com/github/l34130/mise/gradle/run/GradleEnvironmentProvider.kt
- modules/products/idea/src/main/kotlin/com/github/l34130/mise/idea/run/IdeaRunConfigurationExtension.kt
- modules/products/nodejs/src/main/kotlin/com/github/l34130/mise/nodejs/run/NodeRunConfigurationExtension.kt
- modules/products/rider/src/main/kotlin/com/github/l34130/mise/rider/run/RiderPatchCommandLineExtension.kt
- modules/products/toml/src/main/kotlin/com/github/l34130/mise/toml/completion/MiseConfigCompletionProvider.kt
- modules/products/toml/src/main/kotlin/com/github/l34130/mise/toml/editor/MiseRunLineMarkerProvider.kt
> fix: Use mise --env if available

- modules/core/src/main/kotlin/com/github/l34130/mise/core/MiseErrorReportSubmitter.kt
- src/main/resources/META-INF/plugin.xml
- Introduce error reporter for more convenient error reporting
> Introduce error-reporter

- modules/core/src/main/kotlin/com/github/l34130/mise/core/command/MiseCommandLine.kt
> fix: Jackson Deserialization failing on Unknown properties

- .github/workflows/build.yml
- build.gradle.kts
- gradle/libs.versions.toml
> Add detekt

- modules/core/src/main/kotlin/com/github/l34130/mise/core/MiseTaskService.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/lang/completion/MiseTomlTaskDependsCompletionProvider.kt
- src/main/resources/META-INF/plugin.xml
- Support mise file tasks completion.
- Only supports default task directories currently.
> feat: Support Mise File task completions

- src/main/resources/META-INF/plugin.xml
- Fixes: #141 
- The reason was my bad habit, committing with not reviewing all files. Sorry for it.
> fix: Failed to load `MiseTomlDocumentationProvider`

- modules/core/src/main/kotlin/com/github/l34130/mise/core/MiseService.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/PathUtils.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/lang/completion/MiseTomlTaskDependsCompletionProvider.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/lang/psi/MiseTomlPsiUtils.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/model/MiseTask.kt
- Use Task cache
- Sort tasks by its kind (current file -> toml task -> script task)
> feat: Support Shell Script Task Completion

- modules/core/src/main/kotlin/com/github/l34130/mise/core/lang/resolve/MiseTomlTaskDependsReferenceProvider.kt
As we supported reference for the only in the file. now we support over the files.
> feat: Support reference over the files

- modules/core/src/main/kotlin/com/github/l34130/mise/core/MiseService.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/lang/psi/MiseTomlPsiUtils.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/lang/resolve/MiseTaskDocumentationProvider.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/model/MiseTask.kt
- src/main/resources/META-INF/plugin.xml
Support documentation for autocompletions
Closes: #138
> feat: Support documentation

- modules/core/src/main/kotlin/com/github/l34130/mise/core/lang/injection/MiseTomlTaskInjectionContributor.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/lang/psi/MiseTomlPsiPatterns.kt
- src/main/resources/META-INF/plugin.xml
> feat: Support sh language injection

- modules/products/goland/build.gradle.kts
- modules/products/goland/src/test/resources/META-INF/plugin.xml
- modules/products/nodejs/build.gradle.kts
- modules/products/nodejs/src/test/resources/META-INF/plugin.xml
GoLand and NodeJs
- https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-faq.html#missing-opentest4j-dependency-in-test-framework
> fix: retore tests

- modules/core/src/main/kotlin/com/github/l34130/mise/core/MiseService.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/execution/RunMiseTomlTaskAction.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/toolwindow/nodes/MiseRootNode.kt
> fix: Mise Task ToolWindow cannot execute tasks 

- modules/products/nodejs/src/main/kotlin/com/github/l34130/mise/nodejs/node/MiseProjectNodeSetup.kt
> fix: nodejs windows path handling

- modules/core/src/main/kotlin/com/github/l34130/mise/core/MiseService.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/execution/RunMiseTomlTaskAction.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/model/MiseTask.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/model/MiseTaskFile.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/toolwindow/nodes/MiseTaskNode.kt
- modules/core/src/test/kotlin/com/github/l34130/mise/core/FileTestBase.kt
- modules/core/src/test/kotlin/com/github/l34130/mise/core/execution/MiseTomlTaskRunLineMarkerContributorTest.kt
- modules/core/src/test/kotlin/com/github/l34130/mise/core/lang/completion/MiseFileTaskCompletionProviderTest.kt
- modules/core/src/test/kotlin/com/github/l34130/mise/core/lang/completion/MiseShCompletionTestBase.kt
- modules/core/src/test/kotlin/com/github/l34130/mise/core/lang/completion/MiseTomlCompletionTestBase.kt
- modules/core/src/test/kotlin/com/github/l34130/mise/core/lang/completion/MiseTomlTaskDependsCompletionProviderTest.kt
- modules/core/src/test/kotlin/com/github/l34130/mise/core/lang/psi/MiseTomlPsiPatternsTest.kt
- modules/core/src/test/kotlin/com/github/l34130/mise/core/lang/psi/MiseTomlPsiUtilsTest.kt
- modules/core/src/test/resources/META-INF/plugin.xml
fix Unknown type task (CLI sourced task) is cannot run with restoring tests
> fix: Unknown task cannot run

- modules/core/src/main/kotlin/com/github/l34130/mise/core/lang/injection/MiseTomlTaskInjectionContributor.kt
> fix: Some IDEs does not contains ShLanguage as default

- modules/core/src/main/kotlin/com/github/l34130/mise/core/execution/RunMiseTomlTaskAction.kt
> fix: Avoid slow operation on `RunMiseTomlTaskAction`

- modules/core/src/main/kotlin/com/github/l34130/mise/core/command/MiseCommandLine.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/execution/configuration/MiseTomlTaskRunConfiguration.kt
- Support arguument passing on executablePath settings
- Closes: #187
> feat: Support argument passing on executablePath settings

- modules/core/src/main/kotlin/com/github/l34130/mise/core/MiseErrorReportSubmitter.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/MiseHelper.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/command/MiseCommandLine.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/command/MiseCommandLineHelper.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/execution/configuration/MiseTomlTaskRunConfiguration.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/execution/configuration/MiseTomlTaskRunConfigurationEditor.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/notification/MiseNotificationService.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/notification/MiseNotificationServiceUtils.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/run/MiseRunConfigurationSettingsEditor.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/setting/MiseConfigurable.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/setting/MiseSettings.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/setup/AbstractProjectSdkSetup.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/toolwindow/nodes/MiseRootNode.kt
- modules/products/rider/src/main/kotlin/com/github/l34130/mise/rider/run/MiseRiderPatchCommandLineExtension.kt
> refactor: MiseSettings as project scope

- modules/core/src/main/kotlin/com/github/l34130/mise/core/lang/resolve/MiseTomlTaskDependsReferenceProvider.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/model/MiseTask.kt
- modules/core/src/test/kotlin/com/github/l34130/mise/core/model/MiseTomlTableTaskTest.kt
> fix: Arguments to dependencies

- modules/core/src/main/kotlin/com/github/l34130/mise/core/execution/RunMiseTomlTaskAction.kt
> fix: Read access is allowed from inside read-action in RunMiseTomlTaskAction

- modules/core/src/main/kotlin/com/github/l34130/mise/core/MiseErrorReportSubmitter.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/MiseHelper.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/MiseProjectService.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/MiseStartupActivity.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/MiseTomlFileVfsListener.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/command/MiseCommandLine.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/command/MiseCommandLineHelper.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/execution/configuration/MiseTomlTaskRunConfiguration.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/execution/configuration/MiseTomlTaskRunConfigurationEditor.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/lang/completion/MiseTomlTaskCompletionProvider.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/lang/resolve/MiseTaskDocumentationProvider.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/lang/resolve/MiseTomlTaskDependsReferenceProvider.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/notification/MiseNotificationServiceUtils.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/run/MiseRunConfigurationSettingsEditor.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/setting/MiseApplicationSettings.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/setting/MiseConfigurable.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/setting/MiseProjectSettings.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/setting/MiseSettingsListener.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/setup/AbstractProjectSdkSetup.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/toolwindow/nodes/MiseRootNode.kt
- modules/core/src/test/kotlin/com/github/l34130/mise/core/FileTestBase.kt
- modules/core/src/test/kotlin/com/github/l34130/mise/core/MiseServiceTest.kt
- modules/products/diagram/src/main/kotlin/com/github/l34130/mise/diagram/MiseFileTaskGraphDataModel.kt
- modules/products/diagram/src/main/kotlin/com/github/l34130/mise/diagram/MiseFullTaskGraphDataModel.kt
- modules/products/diagram/src/main/kotlin/com/github/l34130/mise/diagram/MiseSingleTaskGraphDataModel.kt
- modules/products/rider/src/main/kotlin/com/github/l34130/mise/rider/run/MiseRiderPatchCommandLineExtension.kt
- modules/products/sh/src/test/kotlin/com/github/l34130/mise/sh/FileTestBase.kt
> fix: Seperate mise executable configuration to application scope

- modules/core/src/main/kotlin/com/github/l34130/mise/core/execution/configuration/MiseTomlTaskRunConfiguration.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/execution/configuration/MiseTomlTaskRunConfigurationEditor.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/setting/MiseApplicationSettings.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/setting/MiseProjectSettings.kt
> fix: Make mise toml task runconfiguration as portable

- modules/core/src/main/kotlin/com/github/l34130/mise/core/lang/structure/MiseTomlFileStructureViewElement.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/lang/structure/MiseTomlFileStructureViewFactory.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/lang/structure/MiseTomlFileStructureViewModel.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/lang/structure/MiseTomlTableEnvStructureViewElement.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/lang/structure/MiseTomlTableTaskStructureViewElement.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/lang/structure/MiseTomlTableToolStructureViewElement.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/model/MiseTomlFile.kt
- src/main/resources/META-INF/plugin.xml
> feat: Support structure

- README.md
- modules/core/src/main/kotlin/com/github/l34130/mise/core/MiseHelper.kt
- modules/products/pycharm/src/main/kotlin/com/github/l34130/mise/pycharm/run/MisePythonExecutionListener.kt
- The bug found while testing for #225
> fix(python): Run configration envvars are not restoring

- modules/core/src/main/kotlin/com/github/l34130/mise/core/command/MiseCommandLine.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/command/MiseCommandLineOutputParser.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/command/MiseTask.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/model/MiseTask.kt
- modules/core/src/test/kotlin/com/github/l34130/mise/core/command/MiseCommandLineOutputParserTest.kt
- modules/products/diagram/src/main/kotlin/com/github/l34130/mise/diagram/MiseFileTaskGraphDataModel.kt
- modules/products/diagram/src/main/kotlin/com/github/l34130/mise/diagram/MiseFullTaskGraphDataModel.kt
- modules/products/diagram/src/main/kotlin/com/github/l34130/mise/diagram/MiseSingleTaskGraphDataModel.kt
- modules/products/diagram/src/main/kotlin/com/github/l34130/mise/diagram/MiseStartupActivity.kt
- modules/products/diagram/src/main/kotlin/com/github/l34130/mise/diagram/MiseTaskGraphEdge.kt
> fix: Invalid thread access for psi

- modules/core/src/main/kotlin/com/github/l34130/mise/core/lang/structure/MiseTomlFileStructureViewElement.kt
- fixes: #232 
I don't know why the ChildrenProvider overrides the reference from [tools, tasks, env] to [env, env, env]. Maybe they are modifying the list with `getValue()`.
[tools, tasks, env] element's value was always same file(TomlFile), and I think that made a breaking the feature.
> fix: `ignore duplicated child at 1: Environment` from AyncTreeModel

- modules/core/src/main/kotlin/com/github/l34130/mise/core/setting/MiseApplicationSettings.kt
> feat: getMiseExecutablePath supports WinGet path resolving

- modules/core/src/main/kotlin/com/github/l34130/mise/core/execution/RunMiseTomlTaskAction.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/model/MiseTask.kt
- modules/products/diagram/src/main/kotlin/com/github/l34130/mise/diagram/MiseStartupActivity.kt
> fix: Read access is allowed from inside read-action only

- modules/core/src/main/kotlin/com/github/l34130/mise/core/util/TerminalUtils.kt
- Resolves: #193
- Resolves: #278
> fix: improve command execution handling in terminal widget

- .idea/gradle.xml
- README.md
- build.gradle.kts
- modules/products/ruby/build.gradle.kts
- modules/products/ruby/src/main/kotlin/com/github/l34130/mise/ruby/run/MiseRubyMineRunConfigurationExtension.kt
- settings.gradle.kts
- src/main/resources/META-INF/mise-ruby.xml
- src/main/resources/META-INF/plugin.xml
> feat: add Ruby support

- README.md
- modules/products/ruby/src/main/kotlin/com/github/l34130/mise/ruby/run/MiseRubyMineRunConfigurationExtension.kt
- modules/products/ruby/src/main/kotlin/com/github/l34130/mise/ruby/sdk/MiseRubyProjectSdkSetup.kt
- src/main/resources/META-INF/mise-ruby.xml
> feat: add Ruby SDK setup support

- modules/core/src/main/kotlin/com/github/l34130/mise/core/lang/psi/MiseTomlPsiPatterns.kt
- modules/products/sh/src/main/kotlin/com/github/l34130/mise/sh/lang/injection/MiseTomlTaskInjectionContributor.kt
> fix: task run string pattern doesn't supports language injection

- modules/core/src/main/kotlin/com/github/l34130/mise/core/command/MiseCommandLineHelper.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/setup/AbstractProjectSdkSetup.kt
- modules/products/goland/src/main/kotlin/com/github/l34130/mise/goland/go/MiseProjectGoSdkSetup.kt
- modules/products/idea/src/main/kotlin/com/github/l34130/mise/idea/jdk/MiseProjectJdkSetup.kt
- modules/products/nodejs/src/main/kotlin/com/github/l34130/mise/nodejs/deno/MiseProjectDenoSetup.kt
- modules/products/nodejs/src/main/kotlin/com/github/l34130/mise/nodejs/node/MiseProjectNodeSetup.kt
- modules/products/pycharm/src/main/kotlin/com/github/l34130/mise/pycharm/sdk/MisePythonSdkSetup.kt
- src/main/resources/META-INF/mise-pycharm.xml
> feat: Python SDK setup with support for uv environment

- modules/core/src/main/kotlin/com/github/l34130/mise/core/model/MiseTask.kt
> fix: PsiElement.getParent() is null

- modules/core/src/main/kotlin/com/github/l34130/mise/core/MiseErrorReportSubmitter.kt
- modules/core/src/main/kotlin/com/github/l34130/mise/core/command/MiseVersion.kt
- Enhance stacktrace with ignoring UI Scheduling related lines.
- Add stackhash field for issue description.
- resolves: #285
> feat: Enhance stacktrace and add stackhash
